name: Format Flow
run-name: ${{ github.actor }} started to format the ${{ github.ref_name }} branch

on:
  push:
    branches:
      - development

permissions:
  actions: write
  contents: write

## https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Node.js v20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: lts/iron

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier . --write

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Commit files
        if: steps.git-check.outputs.modified == 'true'
        id: commit-files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Prettied up files"

      - uses: ad-m/github-push-action@master  
        name: Push changes
        if: ${{steps.commit-files.outcome == 'success'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
